#tomcat
server:
  port: 9090
  servlet:
    context-path: /cloudimpute
spring:
  session:
    store-type: none
  datasource:
#mysql数据源配置
    mysql:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3307/cloudimpute?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  
 #     jdbc-url: jdbc:mysql://127.0.0.1:3306/cloudimpute?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: qwe@11
 #     password: 111111
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

# Java Persistence Api
# Specify the DBMS
  jpa:
    database: mysql
# Show or not log for each sql query
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
# Naming strategy
#[org.hibernate.cfg.ImprovedNamingStrategy  #org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# stripped before adding them to the entity manager)
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

#Mybatis
mybatis:
  configLocation: mybatis-config.xml
  type-aliases-package: my.entity, bigfileupload.entity
  mapper-locations: classpath*:mapper/*.xml
  
  
wrelativePath: E:\项目文档\2022\imputationserver\code1
lrelativePath: /root/cloudimpute/files


